<a href="https://colab.research.google.com/github/shemaaali/DS-Assignment-Submission-Practice-Repository/blob/master/SD_17__LS_DS17_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [130]:
# YOUR WORK HERE
# Here the link of the website for the student performance

!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-06-09 23:59:02--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip.8’

student.zip.8       100%[===================>]  20.00K  --.-KB/s    in 0.04s   

2020-06-09 23:59:02 (535 KB/s) - ‘student.zip.8’ saved [20478/20478]



In [131]:
!unzip student.zip

Archive:  student.zip
replace student-mat.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student-mat.csv         
replace student-por.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student-por.csv         
replace student-merge.R? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student-merge.R         
replace student.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: student.txt             


In [0]:
from scipy import stats
import pandas as pd

In [133]:
df = pd.read_csv('student-mat.csv', sep=';')

print(df.shape)
df.head()

(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [134]:
df['failures'].value_counts().sort_index()

0    312
1     50
2     17
3     16
Name: failures, dtype: int64

In [135]:
df['studytime'].value_counts().sort_index()

1    105
2    198
3     65
4     27
Name: studytime, dtype: int64

In [136]:
contingency = pd.crosstab(df['failures'], df['studytime'])

contingency

studytime   1    2   3   4
failures                  
0          74  158  54  26
1          16   26   7   1
2           6    7   4   0
3           9    7   0   0

In [137]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)


print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table", expected)

chi2 statistic 16.21199080868576
p value 0.06258448399974005
degrees of freedom 9
expected frequencies table [[ 82.93670886 156.39493671  51.34177215  21.32658228]
 [ 13.29113924  25.06329114   8.2278481    3.41772152]
 [  4.51898734   8.52151899   2.79746835   1.16202532]
 [  4.25316456   8.02025316   2.63291139   1.09367089]]


# Conclusion:
Based on the conclusion I can say there is not enough evidence to conclude that (study time and failures) are associated or showed a relationship.They could be more independent.

2) Use Chi^2 tests and stats.chi2_contingency() to identify:

Two pairs of variables that are dependent (are associated with one another)
Two pairs of variables that are independent (have no significant relationship).
Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another?

In [138]:
df['sex'].value_counts()

F    208
M    187
Name: sex, dtype: int64

In [139]:
df['internet'].value_counts()

yes    329
no      66
Name: internet, dtype: int64

In [140]:
contingency = pd.crosstab(df['sex'], df['internet'])
contingency

internet  no  yes
sex              
F         38  170
M         28  159

In [141]:
chi2, p_value, dof, expected = stats.chi2_contingency(contingency)

print("chi2 statistic", chi2)
print("p value", p_value)
print("degrees of freedom",dof)
print("expected frequencies table", expected)

chi2 statistic 0.5500617337279294
p value 0.45829247086513125
degrees of freedom 1
expected frequencies table [[ 34.75443038 173.24556962]
 [ 31.24556962 155.75443038]]


Conclusion:

Based on the conclusion: I can say null hypothesis, these are two variables are "independent" there's no relationship are associated between the two which they are on the same rate. For the alternative hypothesis: the are two variables are "dependent", but there is a relationship associated between between them.

In [142]:
df['sex'].value_counts()

F    208
M    187
Name: sex, dtype: int64

In [143]:
df['internet'].value_counts()

yes    329
no      66
Name: internet, dtype: int64

In [145]:
observed = pd.crosstab(df['sex'], df['internet'])

observed

internet  no  yes
sex              
F         38  170
M         28  159

# **Expected Value Calculation**

In [146]:
observed_with_margins = pd.crosstab(df['sex'], df['internet'], margins=True)

observed_with_margins

internet  no  yes  All
sex                   
F         38  170  208
M         28  159  187
All       66  329  395

In [147]:
observed = observed.values
observed

array([[ 38, 170],
       [ 28, 159]])

In [148]:
observed[1][1]

159

In [149]:
# Calculate the expected rows and columns: (row_total)(column_total) / sample_size 

expected_row1_col1 = 208*66/395


expected_row1_col1


34.754430379746836

In [150]:
row_totals = df['internet'].value_counts().sort_index().values

row_totals

array([ 66, 329])

In [151]:
## This alternative method:- (pulling row totals directly off from the crosstab)
row_totals = observed_with_margins.iloc[2:4, 0:2].values[0]

row_totals

array([ 66, 329])

In [152]:
col_totals = df['sex'].value_counts().sort_index().values

col_totals

array([208, 187])

In [153]:
# alternative method:- (pulling column totals directly off from the crosstab)
col_totals = observed_with_margins.iloc[0:2, 2:3].values.T[0]

col_totals

array([208, 187])

In [154]:
sample_size = df.shape[0]

sample_size

395

In [193]:
expected = np.array([[0,0],
                     [0,0]])

for i, col in enumerate(col_totals):
  for j, row in enumerate(row_totals): 
    expected_value = (row*col / sample_size)
    # print(expected_value, i, j)
    expected[i][j] = expected_value

expected



array([[ 34, 173],
       [ 31, 155]])

In [156]:
observed

array([[ 38, 170],
       [ 28, 159]])

# We can calculate the chi^2 statistic or (test statistic)

In [157]:
((observed - expected)**2 / expected).sum().sum()

0.7686495389163506

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [158]:
# YOUR WORK HERE

import numpy as np

observed = np.array([20,50,30,45,28,61,100])

observed

array([ 20,  50,  30,  45,  28,  61, 100])

In [159]:
n = observed.sum()
n

334

In [160]:
expected_frequency = 334/7

expected_frequency

47.714285714285715

Conclusion:

Based on the null hypothesis: I can say, this is a fair die, expected frequencies == Observed Frequencies which are on the same rate. 
For the alternative hypothesis: I can say, this unfair die, expected frequencies != Observed Frequencies which are on differen relationships.

In [163]:
import numpy as np
from scipy.stats import chisquare  
observed = np.array([[1, 1], [2, 2]]).T
print(observed)
print(chisquare(observed, axis=None))

observed = np.array([20,50,30,45,28,61,100]).T
print(observed)
print(chisquare(observed, axis=None))

[[1 2]
 [1 2]]
Power_divergenceResult(statistic=0.6666666666666666, pvalue=0.8810148425137847)
[ 20  50  30  45  28  61 100]
Power_divergenceResult(statistic=92.07784431137725, pvalue=1.1210658305094777e-17)


## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [169]:
# YOUR WORK HERE
observed = np.array([20,50,30,45,28,61,100])

observed

array([ 20,  50,  30,  45,  28,  61, 100])

In [166]:
expected = np.array([21.16, 21.16, 21.16, 21.16, 21.16, 21.16])

expected

array([21.16, 21.16, 21.16, 21.16, 21.16, 21.16])

In [170]:
# For cell 3 (index position 2)

observed[2] - expected[2]

8.84

In [177]:
observed[2] - expected[2]**2

-417.7456

In [178]:
# See when we squared term makes all the values positive and emphasizes places,
# where we saw a large deviation between observed and expected frequencies.
observed[2] - expected[2]**2 / expected

array([8.84, 8.84, 8.84, 8.84, 8.84, 8.84])

In [180]:
chi2 = ((observed[2] - expected[2])**2 / expected).sum()

chi2

22.158487712665405

Conclusion:

Based on a chi^2 statistic of 22.158 and a p-value of 0, I can say reject the null hypothesis, that observed frequencies are equal to expected frequencies which are on the same relationship,(that means it is a fair die), I can suggest the alternative-method, that is an unfair die which they are on the different relationship.



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)